// all types
export const EDIT_SNAPSHOT = 'EDIT_SNAPSHOT';
export const REMOVE_SNAPSHOT = 'REMOVE_SNAPSHOT';
export const CREATE_STORAGE = 'CREATE_STORAGE';
export const REMOVE_ALL_SNAPSHOT = 'REMOVE_ALL_SNAPSHOT';
export const ROLLBACK_SNAPSHOT = 'ROLLBACK_SNAPSHOT';
export const SHOW_SNAPSHOT_DETAIL = 'SHOW_SNAPSHOT_DETAIL';
