/**
 * Created by ssehacker on 2017/3/21.
 */


// all types
export const VM_TYPE = 'VM';
export const VLAN_TYPE = 'Vlan';
export const IP = 'IP';
export const PPTP = 'pptp';
export const OPENVPN = 'openvpn';
export const MYSQL = 'mysql';
export const LISTEN = 'listen';
export const MYSQLREPLICA = 'mysqlReplica';
export const PHYSICS = 'physics';

export const SAVE_FORMS = 'SAVE_FORMS';
export const PUBLISH_FORMS = 'PUBLISH_FORMS';
export const CLEAR_FORMS = 'CLEAR_FORMS';
export const DELETE_CONNECTION = 'DELETE_CONNECTION';
export const RESTORE_DATA = 'RESTORE_DATA';

export const ADD_BLOCK = 'ADD_BLOCK';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const DYNAMIC = 'DYNAMIC';

export const UPDATE_FORM_IP = 'UPDATE_FORM_IP';
export const DELETE_FORM_IP = 'DELETE_FORM_IP';

export const UPDATE_FORM_VM = 'UPDATE_FORM_VM';
export const DELETE_FORM_VM = 'DELETE_FORM_VM';

export const UPDATE_FORM_HARDDISK = 'UPDATE_FORM_HARDDISK';
export const DELETE_FORM_HARDDISK = 'DELETE_FORM_HARDDISK';

export const UPDATE_FORM_VLAN = 'UPDATE_FORM_VLAN';
export const DELETE_FORM_VLAN = 'DELETE_FORM_VLAN';

export const UPDATE_FORM_BALANCE = 'UPDATE_FORM_BALANCING';
export const ADDLISTENER_FORM_BALANCING = 'ADDLISTENER_FORM_BALANCING';
export const DELETE_FORM_BALANCE = 'DELETE_FORM_BALANCING';

export const UPDATE_FORM_LISTEN = 'UPDATE_FORM_LISTEN';
export const DELETE_FORM_LISTEN = 'DELETE_FORM_LISTEN';
export const MANAGEPOLICY_FORM_LISTEN = 'MANAGEPOLICY_FORM_LISTEN';
export const MANAGEBACKEND_FORM_LISTEN = 'MANAGEBACKEND_FORM_LISTEN';

export const UPDATE_FORM_FIREWALL = 'UPDATE_FORM_FIREWALL';
export const DELETE_FORM_FIREWALL = 'DELETE_FORM_FIREWALL';
export const ADDRULE_FORM_FIREWALL = 'ADDRULE_FORM_FIREWALL';
export const VIEWRULE_FORM_FIREWALL = 'VIEWRULE_FORM_FIREWALL';

export const UPDATE_FORM_ROUTER = 'UPDATE_FORM_ROUTER';
export const DELETE_FORM_ROUTER = 'DELETE_FORM_ROUTER';
export const PPTP_FORM_ROUTER = 'PPTP_FORM_ROUTER';
export const OPENVPN_FORM_ROUTER = 'OPENVPN_FORM_ROUTER';
export const UPDATE_FORM_PPTP = 'UPDATE_FORM_PPTP';
export const DELETE_FORM_PPTP = 'DELETE_FORM_PPTP';
export const MANAGEUSER_FORM_PPTP = 'MANAGEUSER_FORM_PPTP';
export const UPDATE_FORM_OPENVPN = 'UPDATE_FORM_OPENVPN';
export const DELETE_FORM_OPENVPN = 'DELETE_FORM_OPENVPN';

export const UPDATE_FORM_MYSQL = 'UPDATE_FORM_MYSQL';
export const DELETE_FORM_MYSQL = 'DELETE_FORM_MYSQL';
export const CREATEINSTANCE_FORM_MYSQL = 'CREATEINSTANCE_FORM_MYSQL';
export const UPDATE_FORM_MYSQLREPLICA = 'UPDATE_FORM_MYSQLREPLICA';
export const DELETE_FORM_MYSQLREPLICA = 'DELETE_FORM_MYSQLREPLICA';

export const UPDATE_FORM_PHYSICS = 'UPDATE_FORM_PHYSICS';
export const DELETE_FORM_PHYSICS = 'DELETE_FORM_PHYSICS';