// all types
export const CREATE_STORAGE = 'CREATE_STORAGE';
export const EDIT_STORAGE = 'EDIT_STORAGE';
export const REMOVE_STORAGE = 'REMOVE_STORAGE';
export const MANAGE_CONNECTION = 'MANAGE_CONNECTION';
export const CREATE_SNAPSHOOT = 'CREATE_SNAPSHOOT';
export const RESIZE_STORAGE = 'RESIZE_STORAGE';
export const AUTO_SNAPSHOOT = 'AUTO_SNAPSHOOT';
export const COPY_STORAGE = 'COPY_STORAGE';
export const REMOVE_ALL_STORAGE = 'REMOVE_ALL_STORAGE';
export const FETCH_STORAGE_LIST = 'FETCH_STORAGE_LIST';
